// This file is auto-generated by @inlang/paraglide-js
// Do not edit this file manually

import { getLocale } from './runtime.js'

export const messages = {
	"extract.title": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Extract"
		return "Extract"
	},
	"extract.description": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Extract structured data from documents"
		return "Extract structured data from documents"
	},
	"extract.upload": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Upload files"
		return "Upload files"
	},
	"extract.parse": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Parse Only"
		return "Parse Only"
	},
	"extract.extract": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Extract"
		return "Extract"
	},
	"extract.schema": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Schema"
		return "Schema"
	},
	"extract.settings": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Settings"
		return "Settings"
	},
	"extract.progress": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Progress"
		return "Progress"
	},
	"extract.jsonOutput": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "JSON Output"
		return "JSON Output"
	},
	"extract.formatted": (params = {}) => {
		const locale = getLocale()
		if (locale === "en") return "Formatted"
		return "Formatted"
	}
}
