// This file is auto-generated by @inlang/paraglide-js
// Do not edit this file manually

let locale = "en";

export const getLocale = () => locale;

export const setLocale = (newLocale: string) => {
	locale = newLocale;
};

export const locales = ["en"];
