/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VsSplatRouteImport } from './routes/vs/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LlmsVsSplatRouteImport } from './routes/llms.vs.$'
import { Route as LlmsDocsSplatRouteImport } from './routes/llms.docs.$'
import { Route as LlmsBlogSplatRouteImport } from './routes/llms.blog.$'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSplatRoute = VsSplatRouteImport.update({
  id: '/vs/$',
  path: '/vs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsVsSplatRoute = LlmsVsSplatRouteImport.update({
  id: '/llms/vs/$',
  path: '/llms/vs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDocsSplatRoute = LlmsDocsSplatRouteImport.update({
  id: '/llms/docs/$',
  path: '/llms/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsBlogSplatRoute = LlmsBlogSplatRouteImport.update({
  id: '/llms/blog/$',
  path: '/llms/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/vs/$': typeof VsSplatRoute
  '/llms/blog/$': typeof LlmsBlogSplatRoute
  '/llms/docs/$': typeof LlmsDocsSplatRoute
  '/llms/vs/$': typeof LlmsVsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/vs/$': typeof VsSplatRoute
  '/llms/blog/$': typeof LlmsBlogSplatRoute
  '/llms/docs/$': typeof LlmsDocsSplatRoute
  '/llms/vs/$': typeof LlmsVsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/vs/$': typeof VsSplatRoute
  '/llms/blog/$': typeof LlmsBlogSplatRoute
  '/llms/docs/$': typeof LlmsDocsSplatRoute
  '/llms/vs/$': typeof LlmsVsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/vs/$'
    | '/llms/blog/$'
    | '/llms/docs/$'
    | '/llms/vs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/vs/$'
    | '/llms/blog/$'
    | '/llms/docs/$'
    | '/llms/vs/$'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/blog/$'
    | '/docs/$'
    | '/vs/$'
    | '/llms/blog/$'
    | '/llms/docs/$'
    | '/llms/vs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  VsSplatRoute: typeof VsSplatRoute
  LlmsBlogSplatRoute: typeof LlmsBlogSplatRoute
  LlmsDocsSplatRoute: typeof LlmsDocsSplatRoute
  LlmsVsSplatRoute: typeof LlmsVsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$': {
      id: '/vs/$'
      path: '/vs/$'
      fullPath: '/vs/$'
      preLoaderRoute: typeof VsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/vs/$': {
      id: '/llms/vs/$'
      path: '/llms/vs/$'
      fullPath: '/llms/vs/$'
      preLoaderRoute: typeof LlmsVsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/docs/$': {
      id: '/llms/docs/$'
      path: '/llms/docs/$'
      fullPath: '/llms/docs/$'
      preLoaderRoute: typeof LlmsDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/blog/$': {
      id: '/llms/blog/$'
      path: '/llms/blog/$'
      fullPath: '/llms/blog/$'
      preLoaderRoute: typeof LlmsBlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  VsSplatRoute: VsSplatRoute,
  LlmsBlogSplatRoute: LlmsBlogSplatRoute,
  LlmsDocsSplatRoute: LlmsDocsSplatRoute,
  LlmsVsSplatRoute: LlmsVsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
